# Generated by Django 4.2.7 on 2026-03-06 04:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_service_provider_timeslot_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('provider', 'date', 'start_time')},
        ),
    ]
